//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ecommerce.ServiceModel.OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sitecore.net/", ConfigurationName="OrderService.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sitecore.net/IOrderService/GenerateOrderNumber", ReplyAction="http://www.sitecore.net/IOrderService/GenerateOrderNumberResponse")]
        string GenerateOrderNumber(Sitecore.Ecommerce.Services.ServiceClientArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sitecore.net/IOrderService/Create", ReplyAction="http://www.sitecore.net/IOrderService/CreateResponse")]
        System.Data.DataTable Create(System.Data.DataTable shoppingCartData, Sitecore.Ecommerce.Services.ServiceClientArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sitecore.net/IOrderService/Get", ReplyAction="http://www.sitecore.net/IOrderService/GetResponse")]
        System.Data.DataTable Get(string orderNumber, Sitecore.Ecommerce.Services.ServiceClientArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sitecore.net/IOrderService/GetByQuery", ReplyAction="http://www.sitecore.net/IOrderService/GetByQueryResponse")]
        System.Data.DataTable GetByQuery(Sitecore.Ecommerce.Search.Query query, Sitecore.Ecommerce.Services.ServiceClientArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sitecore.net/IOrderService/GetRangeByQuery", ReplyAction="http://www.sitecore.net/IOrderService/GetRangeByQueryResponse")]
        System.Data.DataTable GetRangeByQuery(Sitecore.Ecommerce.Search.Query query, int pageIndex, int pageSize, Sitecore.Ecommerce.Services.ServiceClientArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sitecore.net/IOrderService/GetCount", ReplyAction="http://www.sitecore.net/IOrderService/GetCountResponse")]
        int GetCount(Sitecore.Ecommerce.Search.Query query, Sitecore.Ecommerce.Services.ServiceClientArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sitecore.net/IOrderService/Save", ReplyAction="http://www.sitecore.net/IOrderService/SaveResponse")]
        void Save(System.Data.DataTable orderData, Sitecore.Ecommerce.Services.ServiceClientArgs args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : Sitecore.Ecommerce.ServiceModel.OrderService.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<Sitecore.Ecommerce.ServiceModel.OrderService.IOrderService>, Sitecore.Ecommerce.ServiceModel.OrderService.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateOrderNumber(Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.GenerateOrderNumber(args);
        }
        
        public System.Data.DataTable Create(System.Data.DataTable shoppingCartData, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.Create(shoppingCartData, args);
        }
        
        public System.Data.DataTable Get(string orderNumber, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.Get(orderNumber, args);
        }
        
        public System.Data.DataTable GetByQuery(Sitecore.Ecommerce.Search.Query query, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.GetByQuery(query, args);
        }
        
        public System.Data.DataTable GetRangeByQuery(Sitecore.Ecommerce.Search.Query query, int pageIndex, int pageSize, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.GetRangeByQuery(query, pageIndex, pageSize, args);
        }
        
        public int GetCount(Sitecore.Ecommerce.Search.Query query, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.GetCount(query, args);
        }
        
        public void Save(System.Data.DataTable orderData, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            base.Channel.Save(orderData, args);
        }
    }
}
