//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ecommerce.ServiceModel.OrderProcessorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderProcessorService.IOrderProcessorService")]
    public interface IOrderProcessorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProcessorService/CancelOrder", ReplyAction="http://tempuri.org/IOrderProcessorService/CancelOrderResponse")]
        void CancelOrder(string orderNumber, Sitecore.Ecommerce.Services.ServiceClientArgs args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderProcessorServiceChannel : Sitecore.Ecommerce.ServiceModel.OrderProcessorService.IOrderProcessorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderProcessorServiceClient : System.ServiceModel.ClientBase<Sitecore.Ecommerce.ServiceModel.OrderProcessorService.IOrderProcessorService>, Sitecore.Ecommerce.ServiceModel.OrderProcessorService.IOrderProcessorService {
        
        public OrderProcessorServiceClient() {
        }
        
        public OrderProcessorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderProcessorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CancelOrder(string orderNumber, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            base.Channel.CancelOrder(orderNumber, args);
        }
    }
}
