//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ecommerce.ServiceModel.OrderRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderRepositoryService.IOrderRepositoryService")]
    public interface IOrderRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderRepositoryService/Create", ReplyAction="http://tempuri.org/IOrderRepositoryService/CreateResponse")]
        void Create(string order, Sitecore.Ecommerce.Services.ServiceClientArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderRepositoryService/GetAll", ReplyAction="http://tempuri.org/IOrderRepositoryService/GetAllResponse")]
        string GetAll(string filterExpression, Sitecore.Ecommerce.Services.ServiceClientArgs args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderRepositoryServiceChannel : Sitecore.Ecommerce.ServiceModel.OrderRepositoryService.IOrderRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderRepositoryServiceClient : System.ServiceModel.ClientBase<Sitecore.Ecommerce.ServiceModel.OrderRepositoryService.IOrderRepositoryService>, Sitecore.Ecommerce.ServiceModel.OrderRepositoryService.IOrderRepositoryService {
        
        public OrderRepositoryServiceClient() {
        }
        
        public OrderRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(string order, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            base.Channel.Create(order, args);
        }
        
        public string GetAll(string filterExpression, Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.GetAll(filterExpression, args);
        }
    }
}
