// <auto-generated />
namespace Sitecore.Ecommerce.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DecimalScale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DecimalScale));
        
        string IMigrationMetadata.Id
        {
            get { return "201402131241368_DecimalScale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
