//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ecommerce.ServiceModel.OrderIDGeneratorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderIDGeneratorService.IOrderIDGeneratorService")]
    public interface IOrderIDGeneratorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderIDGeneratorService/Generate", ReplyAction="http://tempuri.org/IOrderIDGeneratorService/GenerateResponse")]
        string Generate(Sitecore.Ecommerce.Services.ServiceClientArgs args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderIDGeneratorServiceChannel : Sitecore.Ecommerce.ServiceModel.OrderIDGeneratorService.IOrderIDGeneratorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderIDGeneratorServiceClient : System.ServiceModel.ClientBase<Sitecore.Ecommerce.ServiceModel.OrderIDGeneratorService.IOrderIDGeneratorService>, Sitecore.Ecommerce.ServiceModel.OrderIDGeneratorService.IOrderIDGeneratorService {
        
        public OrderIDGeneratorServiceClient() {
        }
        
        public OrderIDGeneratorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderIDGeneratorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderIDGeneratorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderIDGeneratorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Generate(Sitecore.Ecommerce.Services.ServiceClientArgs args) {
            return base.Channel.Generate(args);
        }
    }
}
